version: '3'
services:
  api-product:
    build: products/
    ports:
      - "8080:8080"
    env_file:
      - products.env
  redis-products:
    image: "redis:4.0-alpine"
    ports:
      - "6383:6379"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8083:8080
    env_file:
      - swagger.env