---
micronaut:
    application:
        name: products
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

---
redis:
    uri: redis://0.0.0.0:6383
    timeout: 30s